### PR TITLE
Fix app when no training set

### LINKED ISSUE #358: App don't load when there is no training set

### PR DESCRIPTION
**Pull request by gabegma**
Resolve #358 

## Checklist:

You should check all boxes before the PR is ready. If a box does not apply, check it to acknowledge it.

* [x] **ISSUE NUMBER.** You linked the issue number (Ex: Resolve #XXX).
* [x] **PRE-COMMIT.** You ran pre-commit on all commits, or else, you
  ran `pre-commit run --all-files` at the end.
* [x] **USER CHANGES.** The changes are added to CHANGELOG.md and the documentation, if they impact
  our users.
* [x] **DEV CHANGES.**
    * Update the documentation if this PR changes how to develop/launch on the app.
    * Update the `README` files and our wiki for any big design decisions, if relevant.
    * Add unit tests, docstrings, typing and comments for complex sections.

### CODE REVIEW

File: webapp/src/pages/Dashboard.tsx [hunk 1]
```diff
@@ -88,20 +88,21 @@ const Dashboard = () => {
...
-            <Description
-              text="Assess semantic overlap between class pairs and compare to pipeline confusion."
-              link="/class-overlap/"
-            />
-          }
-        >
-          <ClassOverlapTable jobId={jobId} pipeline={pipeline} />
-        </PreviewCard>
-      )}
+      {datasetInfo?.availableDatasetSplits.train &&
```
Comment (JosephMarinier) [inline webapp/src/pages/Dashboard.tsx:91]: Oh we have `availableDatasetSplits`! Cool! I must have been confused with something else. It seems to be handled well in the front end, even for the evaluation set. Good catch for this one!

**Review by JosephMarinier — APPROVED** [review]
Fiou! Thank you! 🙂
