### PR TITLE
Fix config page checkbox fields click event

### LINKED ISSUE #488: Make config checkboxes' "hit box" smaller
The "hit box" of the config checkboxes extends all the way to the right of the page. This can cause some misclicks, for example when simply trying to focus out of a field after editing it (clicking in the void).

https://user-images.githubusercontent.com/8386369/224879228-48e0e7f7-e75b-484b-a3cf-74fd8e171312.mov

### PR DESCRIPTION
**Pull request by nandhinibsn**
Resolve #488 

## Checklist:

You should check all boxes before the PR is ready. If a box does not apply, check it to acknowledge it.

* [x] **ISSUE NUMBER.** You linked the issue number (Ex: Resolve #XXX).
* [x] **PRE-COMMIT.** You ran pre-commit on all commits, or else, you
  ran `pre-commit run --all-files` at the end.
* [x] **USER CHANGES.** The changes are added to CHANGELOG.md and the documentation, if they impact
  our users.
* [x] **DEV CHANGES.**
    * Update the documentation if this PR changes how to develop/launch on the app.
    * Update the `README` files and our wiki for any big design decisions, if relevant.
    * Add unit tests, docstrings, typing and comments for complex sections.

### CODE REVIEW

File: webapp/src/pages/Settings.tsx [hunk 1]
```diff
@@ -689,6 +689,9 @@ const Settings: React.FC<Props> = ({ onClose }) => {
       <DialogContent
         dividers
         sx={{
+          [`& .${formControlLabelClasses.root}`]: {
+            width: "fit-content",
+          },
           [`& .${formControlLabelClasses.labelPlacementStart}`]: {
             justifyContent: "flex-end",
```
Comment (JosephMarinier) [inline webapp/src/pages/Settings.tsx:696]: I think it would be best to work with alignment instead of width. It might be fine with `width`, but I'm afraid it might cause unexpected behaviors.
Since we are inside a "flex" container (`FormGroup`) with the default `align-items: stretch`, we could overwrite this for the `formControlLabelClasses.root` with `align-self: start`.
What's cool is that this works for `formControlLabelClasses.labelPlacementStart` too, to which we can remove the `justify-content: flex-end`.
```suggestion
          [`& .${formControlLabelClasses.root}`]: { alignSelf: "start" },
          [`& .${formControlLabelClasses.labelPlacementStart}`]: {
```

**Review by JosephMarinier — APPROVED** [review]
