### PR TITLE
Fix importing the same proposed actions CSV file twice

### LINKED ISSUE #479: Fix support for importing the same CSV file twice
Bug: When importing a CSV file of proposed actions, importing the same file path twice fails silently. The file browser closes normally but the `fileReader.onload` is never called.
Use case: One might have edited the file and wants to re-import it.
Workaround: Refresh the app.

### PR DESCRIPTION
**Pull request by JosephMarinier**
Resolve #479

## Description:

* [Create reusable component FileInputButton](https://github.com/ServiceNow/azimuth/pull/580/commits/42509e900e1dceaa4dcd891d0be72f5b2859303b) (I will be reusing it in a future PR)
* [Fix uploading same file twice](https://github.com/ServiceNow/azimuth/pull/580/commits/bb26895760eab31a7c1ad6003d74d3ccdd0c9d01)
* [Log changes](https://github.com/ServiceNow/azimuth/pull/580/commits/9dcdc5c0710a8ce4eb95b666984b9eb9576fdd92)

## Checklist:

You should check all boxes before the PR is ready. If a box does not apply, check it to acknowledge it.

* [x] **ISSUE NUMBER.** You linked the issue number (Ex: Resolve #XXX).
* [x] **PRE-COMMIT.** You ran pre-commit on all commits, or else, you
  ran `pre-commit run --all-files` at the end.
* [x] **USER CHANGES.** The changes are added to CHANGELOG.md and the documentation, if they impact
  our users.
* [x] **DEV CHANGES.**
    * Update the documentation if this PR changes how to develop/launch on the app.
    * Update the `README` files and our wiki for any big design decisions, if relevant.
    * Add unit tests, docstrings, typing and comments for complex sections.

### CODE REVIEW

File: webapp/src/components/Analysis/UtterancesTable.tsx [hunk 1]
```diff
@@ -436,35 +437,28 @@ const UtterancesTable: React.FC<Props> = ({
...
-        updateDataAction({
-          ignoreNotFound: true,
-          body,
-          ...getUtterancesQueryState,
-        });
-      }
-    };
-    fileReader.readAsText(file);
+    const body = rows.map((row) => {
+      const [persistentId, dataAction] = row.split(",");
```
Comment (christyler3030) [inline webapp/src/components/Analysis/UtterancesTable.tsx:454]: Is there any other validations necessary here?

**Review by christyler3030 — APPROVED** [review]

File: webapp/src/components/Analysis/UtterancesTable.tsx (hunk 1 above)
Comment (JosephMarinier) [reply webapp/src/components/Analysis/UtterancesTable.tsx:454]: (Just to be sure we're on the same page, I did not change this in this PR.)
Here in the front end, we validate that the CSV headers are exactly as expected, otherwise, we wouldn't know how to parse the file and what to send to the back end. But it stops there.
I think it's fine to let the back end validate the actual values.
For example, we could validate in the front end that the `dataAction` is one of the valid values, but the back end already does it. 🤷
Does that make sense?
